"""v3_add_step6_expectation_vs_reality_to_survey_responses

Revision ID: 0bf785ff0a9c
Revises: e143bd8cc077
Create Date: 2026-04-30 15:06:37.024902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf785ff0a9c'
down_revision: Union[str, Sequence[str], None] = 'e143bd8cc077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step6_expectation_vs_reality', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('step6_expectation_vs_reality')

    # ### end Alembic commands ###
