"""v3_step8_full_expansion_survey_demo_expert_thresholds

Revision ID: 199229e83cbd
Revises: 5de637634b5b
Create Date: 2026-04-30 16:00:54.523648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199229e83cbd'
down_revision: Union[str, Sequence[str], None] = '5de637634b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exit_thresholds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_threshold_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q5_trust_source', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('q6_fairness_pref', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('q7_transparency_pref', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('expert_q1_realism', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expert_q2_barrier', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('expert_q3_comment', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('demo_age_range', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('demo_gender', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('demo_country', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('demo_country')
        batch_op.drop_column('demo_gender')
        batch_op.drop_column('demo_age_range')
        batch_op.drop_column('expert_q3_comment')
        batch_op.drop_column('expert_q2_barrier')
        batch_op.drop_column('expert_q1_realism')
        batch_op.drop_column('q7_transparency_pref')
        batch_op.drop_column('q6_fairness_pref')
        batch_op.drop_column('q5_trust_source')

    with op.batch_alter_table('exit_thresholds', schema=None) as batch_op:
        batch_op.drop_column('entry_threshold_pct')

    # ### end Alembic commands ###
