"""v3_add_confidence_to_prior_expectations

Revision ID: 2ceec84a13ea
Revises: 30b54af63ce1
Create Date: 2026-04-30 10:22:12.125366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ceec84a13ea'
down_revision: Union[str, Sequence[str], None] = '30b54af63ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prior_expectations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prior_expectations', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
