"""v3_add_willingness_measurements

Revision ID: 30b54af63ce1
Revises: 3a211da88f05
Create Date: 2026-04-29 18:09:37.991135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b54af63ce1'
down_revision: Union[str, Sequence[str], None] = '3a211da88f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('willingness_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('willingness_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_willingness_measurements_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('willingness_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_willingness_measurements_session_id'))

    op.drop_table('willingness_measurements')
    # ### end Alembic commands ###
