"""v3_step1_drop_legacy_fields_and_set_nonnull

Revision ID: 3a211da88f05
Revises: 96b3f64d6b1a
Create Date: 2026-04-29 17:51:03.636157

The autogenerated form used bare ``op.drop_column`` / ``op.alter_column``
calls. On SQLite, ``ALTER COLUMN nullable=False`` is not supported and
``DROP COLUMN`` requires 3.35+; both must run inside ``batch_alter_table``
so alembic recreates the table. This file has been hand-converted to that
form (the original autogenerate output is in git history if needed).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a211da88f05'
down_revision: Union[str, Sequence[str], None] = '96b3f64d6b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop v2 building_type/heating, lock v3 ownership_type/occupation NOT NULL."""
    with op.batch_alter_table('user_inputs') as batch_op:
        batch_op.alter_column(
            'ownership_type',
            existing_type=sa.VARCHAR(length=16),
            nullable=False,
        )
        batch_op.alter_column(
            'occupation',
            existing_type=sa.VARCHAR(length=64),
            nullable=False,
        )
        batch_op.drop_column('building_type')
        batch_op.drop_column('heating')


def downgrade() -> None:
    """Restore v2 columns and relax v3 ones to nullable.

    Note: the readded building_type / heating columns are NOT NULL with no
    server_default, so this downgrade will fail on a populated table — same
    behaviour as the autogenerated baseline. If you ever need to roll back
    a populated DB, manually edit this to add server_default values
    ('apartment' / 'district') first.
    """
    with op.batch_alter_table('user_inputs') as batch_op:
        batch_op.add_column(sa.Column('heating', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('building_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column(
            'occupation',
            existing_type=sa.VARCHAR(length=64),
            nullable=True,
        )
        batch_op.alter_column(
            'ownership_type',
            existing_type=sa.VARCHAR(length=16),
            nullable=True,
        )
