"""v3_add_step7_broader_impacts_shift_to_survey_responses

Revision ID: 5de637634b5b
Revises: 841119eecf89
Create Date: 2026-04-30 15:46:18.788632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de637634b5b'
down_revision: Union[str, Sequence[str], None] = '841119eecf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step7_broader_impacts_shift', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('step7_broader_impacts_shift')

    # ### end Alembic commands ###
