"""v3_add_step5_counterfactual_to_survey_responses

Revision ID: 841119eecf89
Revises: 0bf785ff0a9c
Create Date: 2026-04-30 15:23:16.700663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841119eecf89'
down_revision: Union[str, Sequence[str], None] = '0bf785ff0a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step5_q1_counterfactual', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('step5_q2_effort', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('step5_q2_effort')
        batch_op.drop_column('step5_q1_counterfactual')

    # ### end Alembic commands ###
