"""v3_add_session_user_input_fields_and_new_tables

Revision ID: 96b3f64d6b1a
Revises: c98e59de34ef
Create Date: 2026-04-29 17:34:37.440080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b3f64d6b1a'
down_revision: Union[str, Sequence[str], None] = 'c98e59de34ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exit_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('threshold_ratio', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_thresholds_session_id'), 'exit_thresholds', ['session_id'], unique=True)
    op.create_table('prior_expectations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('measurement_round', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prior_expectations_session_id'), 'prior_expectations', ['session_id'], unique=False)
    op.add_column('sessions', sa.Column('country_code', sa.String(length=8), server_default='SE', nullable=False))
    op.add_column('sessions', sa.Column('language', sa.String(length=8), server_default='en', nullable=False))
    op.add_column('sessions', sa.Column('info_calibration_arm', sa.String(length=1), server_default='C', nullable=False))
    op.add_column('sessions', sa.Column('expertise', sa.String(length=16), server_default='general', nullable=False))
    op.add_column('user_inputs', sa.Column('ownership_type', sa.String(length=16), nullable=True))
    op.add_column('user_inputs', sa.Column('occupation', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inputs', 'occupation')
    op.drop_column('user_inputs', 'ownership_type')
    op.drop_column('sessions', 'expertise')
    op.drop_column('sessions', 'info_calibration_arm')
    op.drop_column('sessions', 'language')
    op.drop_column('sessions', 'country_code')
    op.drop_index(op.f('ix_prior_expectations_session_id'), table_name='prior_expectations')
    op.drop_table('prior_expectations')
    op.drop_index(op.f('ix_exit_thresholds_session_id'), table_name='exit_thresholds')
    op.drop_table('exit_thresholds')
    # ### end Alembic commands ###
