"""baseline_v2_schema

Revision ID: c98e59de34ef
Revises: 
Create Date: 2026-04-29 17:00:50.992428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98e59de34ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_breakdowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('energy_purchase', sa.Float(), nullable=False),
    sa.Column('grid_fee', sa.Float(), nullable=False),
    sa.Column('energy_tax', sa.Float(), nullable=False),
    sa.Column('pv_self_consumption', sa.Float(), nullable=False),
    sa.Column('vec_discount', sa.Float(), nullable=False),
    sa.Column('feed_in_income', sa.Float(), nullable=False),
    sa.Column('net_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('rigid_load', sa.Text(), nullable=False),
    sa.Column('flexible_load', sa.Text(), nullable=False),
    sa.Column('pv_generation', sa.Text(), nullable=False),
    sa.Column('net_load', sa.Text(), nullable=False),
    sa.Column('devices', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('original_start', sa.Integer(), nullable=False),
    sa.Column('original_end', sa.Integer(), nullable=False),
    sa.Column('final_start', sa.Integer(), nullable=False),
    sa.Column('final_end', sa.Integer(), nullable=False),
    sa.Column('willing', sa.Boolean(), nullable=True),
    sa.Column('unwilling_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drag_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('from_start', sa.Integer(), nullable=False),
    sa.Column('from_end', sa.Integer(), nullable=False),
    sa.Column('to_start', sa.Integer(), nullable=False),
    sa.Column('to_end', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('retail_price', sa.Text(), nullable=False),
    sa.Column('internal_buy', sa.Text(), nullable=False),
    sa.Column('internal_sell', sa.Text(), nullable=False),
    sa.Column('feed_in_price', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('q1_willingness', sa.String(length=50), nullable=False),
    sa.Column('q2_reasons', sa.Text(), nullable=False),
    sa.Column('q3_concerns', sa.Text(), nullable=False),
    sa.Column('q4_savings_perception', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('building_type', sa.String(length=50), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('heating', sa.String(length=50), nullable=False),
    sa.Column('has_ev', sa.Boolean(), nullable=False),
    sa.Column('has_pv', sa.Boolean(), nullable=False),
    sa.Column('pv_kwp', sa.Float(), nullable=True),
    sa.Column('has_bess', sa.Boolean(), nullable=False),
    sa.Column('bess_kwh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_inputs')
    op.drop_table('survey_responses')
    op.drop_table('shadow_prices')
    op.drop_table('drag_logs')
    op.drop_table('device_shifts')
    op.drop_table('daily_profiles')
    op.drop_table('bill_breakdowns')
    op.drop_table('sessions')
    # ### end Alembic commands ###
