"""v3_add_step4_responses_to_survey_responses

Revision ID: e143bd8cc077
Revises: 2ceec84a13ea
Create Date: 2026-04-30 11:10:42.810653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e143bd8cc077'
down_revision: Union[str, Sequence[str], None] = '2ceec84a13ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step4_q1_shift_intent', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('step4_q2_control_pref', sa.String(length=16), nullable=True))
        batch_op.alter_column('q1_willingness',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('q2_reasons',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('q3_concerns',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('q4_savings_perception',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('q4_savings_perception',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('q3_concerns',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('q2_reasons',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('q1_willingness',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('step4_q2_control_pref')
        batch_op.drop_column('step4_q1_shift_intent')

    # ### end Alembic commands ###
